const SLIDES_LIMIT = 3;
const CAROUSEL_INTERVAL = 5000;
const ALERT_OUT_TIMER = 4000;
const LINKEDIN_COMPANY_ID = 68737437;
const TWITTER_WIDGET_WIDTH = 314;

export {
  SLIDES_LIMIT,
  CAROUSEL_INTERVAL,
  ALERT_OUT_TIMER,
  LINKEDIN_COMPANY_ID,
  TWITTER_WIDGET_WIDTH,
};
