//Donation texts
const DEFAULT_DONATION_MESSAGE = "¡Contribuye!";
const DEFAULT_DONATION_BUTTON_TEXT = "Contribuir";
const DEFAULT_THANKS_DONATION_MESSAGE = "¡Muchas gracias por contribuir!";

export {
  DEFAULT_DONATION_MESSAGE,
  DEFAULT_THANKS_DONATION_MESSAGE,
  DEFAULT_DONATION_BUTTON_TEXT,
};
