export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOCAL_STORAGE_AUTH_KEY = "LOCAL_STORAGE_AUTH_KEY"
export const USER_CURRENT_KEY = "USER_CURRENT_KEY"
